### PR TITLE
add sample CMakeLists.txt

### PR DESCRIPTION
**Pull request by adriweb**
Hi,

This is just to make it easier to import the project into IDEs, for instance, or to build with luajit-based setups :)
I didn't add support for other Lua versions, but I suppose that's a good base for now?

### CODE REVIEW

**Comment by zhaozg** [comment]
Welcome PR, please try to make CI green before merge this.

**Comment by adriweb** [comment]
Hi, CI was already broken because of unrelated issues on some configurations with OpenSSL. For instance see before: https://travis-ci.org/zhaozg/lua-openssl/builds
In fact this PR has files that are not used during CI.

**Comment by adriweb** [comment]
argh, cmake 2.8 is like 8 years old, I'm not even sure i can find a way to test it. But we can try.

**Comment by zhaozg** [comment]
> argh, cmake 2.8 is like 8 years old, I'm not even sure i can find a way to test it. But we can try.

Don't worry about it, I merge.

**Comment by adriweb** [comment]
Ok thanks. 
FYI, I use this CMakeLists on a project built by yocto as part of a dependency, so we know it is working. If you want I can share the bitbake recipe but I think that's a bit outside of the scope 🤷‍♂️

**Pull request merged**
