### PR TITLE
make compatible with Lua 5.3

### PR DESCRIPTION
**Pull request by witchu**
- upgrade to lua-compat-5.3
- add macro luaL_checkint, luaL_optint, luaL_checklong, luaL_optlong
- move variable declarations to begin of the block (can't compile with msvc2008)

### CODE REVIEW

**Comment by zhaozg** [comment]
looks good,  please combine all commit into one, then I'll merge this.

**Comment by zhaozg** [comment]
Thanks your work, and looks good,  please combine commits into one, then I'll merge this.

**Comment by witchu** [comment]
How to combine commits?

Thanks

**Comment by witchu** [comment]
ok. I just added --force.

**Comment by zhaozg** [comment]
> ok. I just added --force.

That's right.

**Pull request merged**
