### PR TITLE
fix compilation without deprecated OpenSSL APIs

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by zhaozg** [comment]
Thanks your PR. please wait some time for tuning CI.

**Comment by neheb** [comment]
OK. I had a thought about simplifying the patch.

EVP_CIPHER_CTX_free() in OpenSSL 1.1 is the same as

EVP_CIPHER_CTX_cleanup()
OPENSSL_free()

So maybe get rid of _cleanup() ?

**Comment by zhaozg** [comment]
> OK. I had a thought about simplifying the patch.

1. 目标 
  * 支持OpenSSL 1.0.2之后的所有版本的 OpenSSL.
  * 支持 libreessl
2. 实现上，可以考虑使用一些兼容接口，可以参考: https://github.com/zhaozg/lua-openssl/blob/master/src/compat.c 就是简单地为特定版本做点封装而已。

**Comment by neheb** [comment]
Figured it out. ENGINE_register_all_complete does not include the OpenSSL engine oddly enough...

ENGINE_load_builtin_engines() includes everything except OpenSSL and AFALG. Interesting...

**Comment by zhaozg** [comment]
> Figured it out. ENGINE_register_all_complete does not include the OpenSSL engine oddly enough...
> 
> ENGINE_load_builtin_engines() includes everything except OpenSSL and AFALG. Interesting...

从字面来看，这两个 API 是包括载入 openssl 引擎的， 在lua-openssl 效果应该是一样的。

**Pull request merged**
